=== api-evangelist/apache-flink/json-schema/flink-rest-io-metrics-info-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/apache-flink/refs/heads/main/json-schema/flink-rest-io-metrics-info-schema.json",
  "title": "IOMetricsInfo",
  "description": "IOMetricsInfo schema from Apache Flink REST API",
  "type": "object",
  "properties": {
    "accumulated-backpressured-time": {
      "type": "integer",
      "format": "int64"
    },
    "accumulated-busy-time": {
      "type": "number",
      "format": "double"
    },
    "accumulated-idle-time": {
      "type": "integer",
      "format": "int64"
    },
    "read-bytes": {
      "type": "integer",
      "format": "int64"
    },
    "read-bytes-complete": {
      "type": "boolean"
    },
    "read-records": {
      "type": "integer",
      "format": "int64"
    },
    "read-records-complete": {
      "type": "boolean"
    },
    "write-bytes": {
      "type": "integer",
      "format": "int64"
    },
    "write-bytes-complete": {
      "type": "boolean"
    },
    "write-records": {
      "type": "integer",
      "format": "int64"
    },
    "write-records-complete": {
      "type": "boolean"
    }
  }
}

=== api-evangelist/apache-flink/examples/flink-rest-io-metrics-info-example.json
{
  "accumulated-backpressured-time": 1,
  "accumulated-busy-time": 1.0,
  "accumulated-idle-time": 1,
  "read-bytes": 1,
  "read-bytes-complete": true,
  "read-records": 1,
  "read-records-complete": true,
  "write-bytes": 1,
  "write-bytes-complete": true,
  "write-records": 1,
  "write-records-complete": true
}
